version: '3'
services:
  clamav:
    build:
      context: ./backends/clamav
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  kvrt:
    build:
      context: ./backends/kvrt
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
